# Generated by Django 5.2.4 on 2025-07-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aprendices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=255)),
                ('nombres', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=225)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ciudad', models.CharField(max_length=155)),
                ('programa', models.CharField(max_length=255)),
            ],
        ),
    ]
