# Generated by Django 5.2.4 on 2025-07-30 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aprendices', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='aprendices',
            new_name='Aprendiz',
        ),
    ]
