# Generated by Django 5.2.4 on 2025-07-31 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20, unique=True)),
                ('tipo_documento', models.CharField(choices=[('CC', 'cedula de ciudania'), ('CE', 'cedula de extranjeria'), ('TI', 'Tarjeta de identidad'), ('PAS', 'pasaporte')], default='CC', max_length=3)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15)),
                ('correo', models.EmailField(max_length=50)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('ciudad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=30, null=True)),
                ('nivel_educativo', models.CharField(choices=[('TEC', 'Tecnico'), ('TGL', 'Tecnologo'), ('PRE', 'Pregrado'), ('ESP', 'Especialización'), ('MAE', 'Maestria'), ('DOC', 'Doctorado')], default='MAE', max_length=3)),
                ('especialidad', models.CharField(max_length=50)),
                ('años_experiencia', models.CharField(max_length=4)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_vinculacion', models.DateField(null=True)),
            ],
        ),
    ]
