# Generated by Django 5.2.4 on 2025-07-31 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nivel_formacion', models.CharField(choices=[('AUX', 'Auxiliar'), ('OPE', 'Operario'), ('TEC', 'Tecnico'), ('TGL', 'Tecnologo'), ('ESP', 'Especializacion tecnologica'), ('COM', 'Complementario')], max_length=3)),
                ('modalidad', models.CharField(choices=[('PRE', 'Presencial'), ('VIR', 'Virtual'), ('MIX', 'Mixta')], max_length=3)),
                ('duracion_meses', models.PositiveIntegerField(verbose_name='duracion en meses')),
                ('duracion_horas', models.PositiveIntegerField(verbose_name='Duarcion  en horas')),
                ('descripcion', models.TextField(verbose_name='Descripcion del programa')),
                ('competencias', models.TextField(verbose_name='Competencias del programa')),
                ('perfil_egreso', models.TextField(verbose_name='Perfil de egreso')),
                ('requisitos_ingreso', models.TextField(verbose_name='requisistos para entrar al programa')),
                ('centro_formacion', models.CharField(max_length=200)),
                ('regional', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('ACT', 'Activo'), ('INA', 'Inactivo'), ('SUS', 'Suspendido'), ('CAN', 'Cancelado')], default='ACT', max_length=3)),
                ('fecha_creacion', models.DateField(verbose_name='fecha de creacion del programa')),
                ('fecha_registro', models.DateField(verbose_name='fecha de registro')),
            ],
        ),
    ]
